// src/app/terms/page.tsx
import React from 'react';
import Link from 'next/link';

export const metadata = {
  title: 'Terms & Conditions – Ingrox',
  description: 'Read the terms and conditions for using Ingrox.',
};

export default function TermsPage() {
  const s = { fontSize: 14, color: '#555', lineHeight: 1.75, marginBottom: 16 };
  const h2: React.CSSProperties = { fontSize: 16, fontWeight: 500, marginBottom: 8, marginTop: 28, color: '#1a1a1a' };
  return (
    <div style={{ minHeight: '100vh', background: '#F5F4F0' }}>
      <nav style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '13px 40px', borderBottom: '0.5px solid rgba(0,0,0,0.1)', background: '#fff' }}>
        <Link href="/" style={{ fontSize: 16, fontWeight: 600 }}>Ing<span style={{ color: '#534AB7' }}>rox</span></Link>
        <Link href="/" style={{ fontSize: 13, color: '#555' }}>← Back to home</Link>
      </nav>
      <div style={{ maxWidth: 680, margin: '0 auto', padding: '48px 24px' }}>
        <div style={{ background: '#fff', borderRadius: 12, border: '0.5px solid rgba(0,0,0,0.1)', padding: '36px 40px' }}>
          <h1 style={{ fontSize: 24, fontWeight: 500, marginBottom: 6 }}>Terms & Conditions</h1>
          <p style={{ fontSize: 12, color: '#888', marginBottom: 28 }}>Last updated: January 2025</p>

          <p style={s}>By using Ingrox you agree to these terms. Please read them carefully.</p>

          <h2 style={h2}>Service description</h2>
          <p style={s}>Ingrox provides business data analysis and insights for small D2C businesses. We compare your weekly revenue and order data and generate plain-language recommendations.</p>

          <h2 style={h2}>Not financial or business advice</h2>
          <p style={s}>Insights generated by Ingrox are informational only. They are not professional financial, legal, or business advice. You remain solely responsible for all business decisions you make. Ingrox is not liable for outcomes resulting from actions taken based on these insights.</p>

          <h2 style={h2}>Data accuracy</h2>
          <p style={s}>Insights are only as accurate as the data you enter. We do not verify the accuracy of data you provide. Incorrect input will produce incorrect output.</p>

          <h2 style={h2}>Acceptable use</h2>
          <p style={s}>You agree not to use Ingrox to submit false data, attempt to reverse-engineer the platform, or violate any applicable laws. One account per business. You must be at least 18 years old to use the service.</p>

          <h2 style={h2}>Availability</h2>
          <p style={s}>We aim for high availability but do not guarantee uninterrupted access. We may update, modify, or discontinue features with reasonable notice.</p>

          <h2 style={h2}>Limitation of liability</h2>
          <p style={s}>Ingrox's liability is limited to the amount paid (if any) in the 12 months preceding any claim. We are not liable for indirect, consequential, or incidental damages.</p>

          <h2 style={h2}>Changes to terms</h2>
          <p style={s}>We may update these terms. Continued use after changes constitutes acceptance. Major changes will be communicated by email.</p>

          <h2 style={h2}>Contact</h2>
          <p style={s}>For any legal questions, email <a href="mailto:info.growlytic@gmail.com" style={{ color: '#534AB7' }}>info.growlytic@gmail.com</a>.</p>
        </div>
      </div>
    </div>
  );
}
